### ISSUE TITLE
Incorrect TITANIUM_SDK path

### ISSUE THREAD

**Issue by av-k** [gabrielpjensen/card_module#1]
Your:
`TITANIUM_SDK = /Users/xxx/Library/Application Support/Titanium/mobilesdk/osx/7.4.0.GA`
Correct:
`TITANIUM_SDK = ~/Library/Application Support/Titanium/mobilesdk/osx/7.4.0.GA`
or
`TITANIUM_SDK = $HOME/Library/Application Support/Titanium/mobilesdk/osx/7.4.0.GA`

**Comment by topothesia-development** [comment]
Thanks av-k.
